### ISSUE TITLE
開発環境

### ISSUE THREAD

**Issue by hiroto0222** [hiroto0222/RogueLike#4]
必要:
- Omnisharp
- Unity + VS Code 連携
- Unity V2022.3.4f1
- .NET SDK

VSCode 拡張機能
- C# Dev Kit (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit)
- Unity

Unity Packages:
-

**Comment by Hiromu009** [comment]
マウス座標にキャラクターを動かすコード

- https://tanisugames.com/mouse-move/

**Comment by hiroto0222** [comment]
Issue の件と関係ないのでコメント消去してください

**Comment by Hiromu009** [comment]
悲しいです
